### ISSUE TITLE
Can't register iOS native app URI. "Create New App" form is restricted to `https://` URIs.

### ISSUE THREAD

**Issue by olutsenko** [NeatoRobotics/neato-sdk-ios#1]
Hello,

I am having some troubles regarding the app URI redirect setup.

When registering an app on Developer Portal, you are required to enter `https://` based URI. The form rejects app url schemes like `my-app://`.

At the same time SDK manual suggests to provide native app URI scheme.

So at he moment my setup is:

- Registered app with `https://` url
- And app with URI scheme my-app://
- NeatoSDK configured with app URI scheme `my-app://`

After calling `presentLoginController` I get a login page. After login I get an error message "The redirect uri included is not valid."

How can I register my app URI to overcome this issue?

Thanks!

Cheers,
Oleg

**Comment by ariok** [comment]
Hey Oleg, 
the redirect URI should contains a path after the URI schema, like `my-app://mypath` and not just `my-app://`. Is that what you are referring to?

**Comment by olutsenko** [comment]
Indeed, this helps! Thanks a lot!
